apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels: { app: payment }
spec:
  replicas: 3
  selector: { matchLabels: { app: payment } }
  template:
    metadata:
      labels: { app: payment }
    spec:
      containers:
      - name: payment
        image: myregistry/payment:latest
        ports: [{ containerPort: 8080 }]
        livenessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet: { path: /ready, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 5
